In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [ ]:
df = pd.read_csv('mining_distribution_dataset.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314 entries, 0 to 313
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                314 non-null    object
 1   Shipping Volume     314 non-null    float64
 2   Stock               314 non-null    float64
 3   Transport Capacity  314 non-null    float64
 4   Loading Time        314 non-null    float64
 5   Weather             314 non-null    object
dtypes: float64(4), object(2)
memory usage: 14.8+ KB

In [ ]:
df = df.drop(columns=["Date"])

weather_order = {'Light Rain': 0, 'Cloudy': 1, 'Sunny': 2}
df['Weather_Encoded'] = df['Weather'].map(weather_order)

df.drop(columns=['Weather'], inplace=True)

df.head(10)

   Shipping Volume   Stock  Transport Capacity  Loading Time  Weather_Encoded
0           119.02  145.29             82.7650        190.84                0
1           113.13  127.01             78.1900        126.64                2
2           126.26  156.20             78.0875        163.78                1
3            73.97   94.44             64.0450         97.32                0
4            70.56   99.50             46.9375        124.53                0
5           142.68  156.10            107.2900        217.98                1
6           123.43  138.09             76.9625        222.45                1
7           135.72  180.84            103.4650        144.22                0
8           113.40  121.64             84.2900        143.95                1
9            94.72   99.67             67.8750        154.73                2

In [ ]:
X = df[['Stock', 'Transport Capacity', 'Loading Time', 'Weather_Encoded']]
Y = df['Shipping Volume']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=621)

X_scaler = StandardScaler()
X_scaler.fit(X_train)

Y_scaler = StandardScaler()
Y_scaler.fit(y_train.values.reshape(-1, 1))

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

y_train_scaled = Y_scaler.transform(y_train.values.reshape(-1, 1))
y_test_scaled = Y_scaler.transform(y_test.values.reshape(-1, 1))

In [ ]:
model = LinearRegression()
model.fit(X_train_scaled, y_train_scaled)

y_pred_scaled = model.predict(X_test_scaled)

y_pred = Y_scaler.inverse_transform(y_pred_scaled)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mae)
print("R-squared:", r2)

Mean Squared Error: 5.007295133549964
R-squared: 0.9049541141886527

# SVM Scaled

In [ ]:
from sklearn import svm

model = svm.SVR(kernel='poly')
model.fit(X_train_scaled, y_train_scaled.ravel())

y_pred_scaled = model.predict(X_test_scaled)
y_pred = Y_scaler.inverse_transform(y_pred_scaled.reshape(-1, 1))

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R-squared:", r2)

test_predict = model.predict(X_scaler.transform([[24, 29, 35, 22]]))

print(Y_scaler.inverse_transform(test_predict.reshape(-1, 1)))

Mean Absolute Error: 5.804044801356153
R-squared: 0.8517410726457715
[[17790.32417064]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

# SVM Unscaled

In [ ]:
model = svm.SVR(kernel='linear')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R-squared:", r2)

test_predict = model.predict([[120, 10, 8, 2]])

print(test_predict)

Mean Absolute Error: 5.045388677689219
R-squared: 0.9010382686122661
[74.67533265]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mae)
print("R-squared:", r2)

Mean Squared Error: 4.234447619047621
R-squared: 0.9092916519152674

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mae)
print("R-squared:", r2)

Mean Squared Error: 3.8209615466792837
R-squared: 0.9299230870004462

# Polynomial Regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

model = Pipeline([('poly', PolynomialFeatures(degree=2)),
                  ('linear', LinearRegression(fit_intercept=False))])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R Squared:", r2)

test_predict = model.predict([[120, 10, 26, 1]])

print(test_predict)

Mean Absolute Error: 2.6643059076290463
R Squared: 0.9667322745772319
[34.95536402]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(

In [ ]:
import pickle

with open('shipping.pkl', 'wb') as f:
    pickle.dump(model, f)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mae)
print("R Squared:", r2)

Mean Squared Error: 4.830920634920638
R Squared: 0.8936889691081755

In [ ]:
df.corr()

,Shipping Volume,Stock,Transport Capacity,Loading Time,Weather_Encoded
Shipping Volume,1.000000,0.857704,0.711970,0.692023,0.458282
Stock,0.857704,1.000000,0.478614,0.461512,0.231870
Transport Capacity,0.711970,0.478614,1.000000,0.495582,0.231126
Loading Time,0.692023,0.461512,0.495582,1.000000,0.331335
Weather_Encoded,0.458282,0.231870,0.231126,0.331335,1.000000